# Generated by Django 5.1.6 on 2025-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_facility_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expense_proof',
            field=models.FileField(blank=True, null=True, upload_to='expense_proofs/'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsorship_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='utilization_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
