# Generated by Django 5.1.6 on 2025-02-23 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_nomination_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='end_date',
            new_name='nomination_start_date',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='start_date',
            new_name='voting_end_date',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='voter',
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='election',
            name='is_active',
        ),
        migrations.AddField(
            model_name='election',
            name='voting_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='nomination_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='admin_remarks',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomination',
            name='manifesto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='nominations/'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('election', 'voter')},
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_count', models.IntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('nomination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.nomination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('election', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate'),
        ),
    ]
