# Generated by Django 5.1.6 on 2025-02-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty-sports', 'Faculty - Sports'), ('faculty-lab', 'Faculty - Lab'), ('faculty-transport', 'Faculty - Transport'), ('faculty-hod', 'Faculty - HOD'), ('faculty-teaching', 'Faculty - Teaching Staff'), ('admin', 'Administrator'), ('staff', 'Staff')], max_length=20),
        ),
    ]
