# Generated by Django 5.1.6 on 2025-02-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_year',
            field=models.CharField(blank=True, choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Fourth Year')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
