# Generated by Django 5.1.6 on 2025-02-23 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('violation_type', models.CharField(choices=[('exam_cheating', 'Examination Cheating'), ('plagiarism', 'Plagiarism'), ('impersonation', 'Impersonation'), ('unauthorized_materials', 'Unauthorized Materials'), ('electronic_device', 'Electronic Device Usage'), ('collusion', 'Collusion'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('severe', 'Severe')], max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, upload_to='cheating_evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_investigation', 'Under Investigation'), ('hearing_scheduled', 'Hearing Scheduled'), ('resolved', 'Resolved'), ('appealed', 'Under Appeal'), ('closed', 'Case Closed')], default='pending', max_length=20)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheating_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reported'],
                'permissions': [('can_view_all_cases', 'Can view all cheating cases'), ('can_manage_cases', 'Can manage cheating cases'), ('can_resolve_cases', 'Can resolve cheating cases')],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('grounds', models.TextField()),
                ('supporting_evidence', models.FileField(blank=True, upload_to='appeal_evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='academic_integrity.cheatingcase')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(choices=[('warning', 'Written Warning'), ('zero_grade', 'Zero Grade in Exam'), ('course_failure', 'Course Failure'), ('suspension', 'Temporary Suspension'), ('expulsion', 'Expulsion'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='academic_integrity.cheatingcase')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_sanctions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
